import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { minimatch } from "minimatch";
import { stage1 } from "../src/stages/stage1_difftastic.js";
import { Delta } from "../src/stages/types.js";
import { testConfig } from "./helpers.js";

/**
 * Scope guards for the trivial classes — the one place where a file is preserved on its PATH
 * rather than on proof that its content did not change. Anything reachable here is preserved
 * WITHOUT a human looking at it, so the matching rules have to be narrow by construction.
 *
 * These exist because the shipped config previously listed `docs/**`, which made EVERY file under
 * docs/ trivial: `docs/deploy.sh`, `docs/Dockerfile`, even `docs/.github/workflows/x.yml`. A PR
 * adding an executable payload under docs/ would have kept its approval.
 */
describe("shipped config: trivial-class scope", () => {
  const cfg = JSON.parse(readFileSync("config/config.json", "utf8"));
  const docs: string[] = cfg.trivialClasses.docs;
  const isDoc = (f: string) => docs.some((g) => minimatch(f, g, { dot: true }));

  const mustNotBeTrivial = [
    "docs/deploy.sh",
    "docs/Dockerfile",
    "docs/ci/run.py",
    "docs/.github/workflows/x.yml",
    "docs/secrets.env",
    "docs/Makefile",
    "docs/index.js",
  ];
  for (const f of mustNotBeTrivial) {
    it(`does not treat ${f} as documentation`, () => {
      expect(isDoc(f)).toBe(false);
    });
  }

  const mustBeTrivial = ["docs/guide.md", "README.md", "notes.txt", "docs/api/reference.mdx"];
  for (const f of mustBeTrivial) {
    it(`still treats ${f} as documentation`, () => {
      expect(isDoc(f)).toBe(true);
    });
  }

  it("no trivial-class glob matches a whole directory", () => {
    // A bare `dir/**` entry ignores file type entirely, which is how the docs hole appeared.
    // Every documentation pattern must constrain the extension.
    for (const g of docs) expect(g).toMatch(/\.[a-z]+$/i);
  });
});

function delta(files: string[], authors: (string | null)[]): Delta {
  return {
    repo: "o/r", approvedSha: "a".repeat(40), headSha: "b".repeat(40),
    changedFiles: files, addedLines: 1, removedLines: 0,
    commitAuthors: authors, prAuthor: "dev",
    forcePushed: false, baseChanged: false,
    patchByFile: Object.fromEntries(files.map((f) => [f, "+x\n"])),
  };
}

/**
 * Generated artifacts are preserved on filename, so the authorship constraint is the only thing
 * separating "CI regenerated a protobuf stub" from "a human hand-edited a file named *.gen.ts and
 * put code in it". `requireDeterministicRegen` cannot verify anything on its own — nothing re-runs
 * the generator — so it must not be sufficient by itself.
 */
describe("generated-file trivial class requires machine authorship", () => {
  const cfg = () => {
    const c = testConfig();
    c.trivialClasses.generated = {
      files: ["**/*.gen.ts", "**/*.pb.go"],
      requireDeterministicRegen: true,
      requireBotAuthor: ["github-actions[bot]"],
    };
    return c;
  };

  it("preserves a generated file regenerated by the bot", async () => {
    const d = await stage1(delta(["src/api.gen.ts"], ["github-actions[bot]"]), cfg());
    expect(d?.reason).toBe("trivial_class");
  });

  it("does NOT preserve a generated file hand-edited by a human", async () => {
    const d = await stage1(delta(["src/api.gen.ts"], ["dev"]), cfg());
    expect(d).toBeNull(); // falls through for real evaluation
  });

  it("does NOT preserve when authorship is unattributable", async () => {
    const d = await stage1(delta(["src/api.gen.ts"], [null]), cfg());
    expect(d).toBeNull();
  });

  it("does NOT preserve when the commit list is empty (vacuous every())", async () => {
    const d = await stage1(delta(["src/api.gen.ts"], []), cfg());
    expect(d).toBeNull();
  });

  it("does NOT preserve when no bot allowlist is configured", async () => {
    const c = cfg();
    c.trivialClasses.generated.requireBotAuthor = [];
    const d = await stage1(delta(["src/api.gen.ts"], ["github-actions[bot]"]), c);
    expect(d).toBeNull();
  });
});
